force-app/main/default/objects/Trigger_conf__c/Trigger_conf__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores configuration for Apex trigger</description>
    <label>Trigger Conf</label>
</CustomObject>

force-app/main/default/objects/Trigger_conf__c/fields/SkipTriggerUsernames__c.field-meta.xml
<CustomField>
    <fullName>SkipTriggerUsernames__c</fullName>
    <inlineHelpText>CSV Usernames for trigger skip</inlineHelpText>
    <label>Usernames to Trigger Skip</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Trigger_conf__c/fields/TiggerHandlerClass__c.field-meta.xml
<CustomField>
    <fullName>TiggerHandlerClass__c</fullName>
    <inlineHelpText>Specify name of apex handler class which implements ITrigger interface</inlineHelpText>
    <label>Apex Handler</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerFactory.cls
/**
 * 
 */
public with sharing class TriggerFactory
{
    public static void initiateHandler(Schema.sObjectType soType)
    {
        Trigger_conf__c triggerConfig = Trigger_conf__c.getInstance(soType + '');
        if(triggerConfig != null && 
            isTriggerDisabledForUser(triggerConfig) == false){
                
            TriggerInterface handler = getHandler(triggerConfig);
            
            if (handler != null)
            {
                execute(handler);
            }
        }
    }

    private static Boolean isTriggerDisabledForUser(Trigger_conf__c config){
        return (String.IsNotBlank(config.SkipTriggerUsernames__c) &&
                config.SkipTriggerUsernames__c.containsIgnoreCase(UserInfo.getUserName())) ;
    }

    private static void execute(TriggerInterface handler)
    {

        if (Trigger.isBefore)
        {   
            if (Trigger.isDelete)
            {
                handler.beforeDelete(Trigger.old);
            }
            else if (Trigger.isInsert)
            {
                handler.beforeInsert(Trigger.new);
            }
            else if (Trigger.isUpdate)
            {
                handler.beforeUpdate(Trigger.new, Trigger.oldmap);
            }
        }
        else
        {
            if (Trigger.isDelete)
            {
                    handler.afterDelete(Trigger.old);
            }
            else if (Trigger.isInsert)
            {
                handler.afterInsert(Trigger.new);
            }
            else if (Trigger.isUpdate)
            {
                handler.afterUpdate(Trigger.new, Trigger.oldmap);
            }
        }
    }

    private static TriggerInterface getHandler(Trigger_conf__c config)
    {
        TriggerInterface handler;

        if(String.isNotBlank(config.TiggerHandlerClass__c)){
            Type t = Type.forName(config.TiggerHandlerClass__c);

            Object typeInstance = t.newInstance();
            
            if(t != null && typeInstance instanceof TriggerInterface){
                handler = (TriggerInterface) typeInstance;
            }
            else{
                system.debug('WARNING: Handler ' + config.TiggerHandlerClass__c + ' for Sobject ' + config.name + ' does not inherit IHandler interface');
            }
        }

        return handler; 
    }
}